### ISSUE TITLE
First presentation slide using codio

### ISSUE THREAD

**Issue by rhelmstedter** [vinayak-mehta/present#72]
I teach coding at a middle school. I made this welcome slide for students to see as they join our zoom class. 

![Welcome](https://user-images.githubusercontent.com/70656244/92018192-b081b300-ed09-11ea-8b1e-0f33ae3adf0f.gif)

Slide markdown and text of .yml file below. 

---

```
<!-- fg=green bg=black -->
# Welcome to Coding
![codio](start_class.yml)
```

--- 
[//]: # (below is the start_class.yml text)

```
speed: 6
lines:
- prompt: Mr.H $
  in: pwd
  color: green
- out: '    home'
  color: green
  bold: True
- prompt: Mr.H $
  in: cd DATA/coding/
  color: green
- out: '    cwd = DATA/coding/'
  color: green
  bold: True
- prompt: Mr.H $
  in: run --start_class
  color: green
- out: '    Please Login to Canvas'
  color: green
  bold: True
- out: '    Students are logging in'
  color: green
  bold: True
- progress: true
  progressChar: █
```
